/***************************************************************************//**
 * File pattern.h
 * 
 * Description: User Interface Pattern header
 *
 *
 ******************************************************************************/

#ifndef __UI_PATTERN_HEADER__
#define __UI_PATTERN_HEADER__





/*  led1_blink
 *  Total Values: 110
 *  Total Generated Bytes: 28
 */ 
const I8U led1_blink[] = {192,0,12,0,0,128,0,8,0,0,64,0,0,0,0,0,0,4,0,0,64,0,8,0,0,128,0,0};


/*  led2_blink
 *  Total Values: 100
 *  Total Generated Bytes: 25
 */ 
const I8U led2_blink[] = {176,0,11,0,0,160,0,10,0,0,144,0,8,0,0,128,0,9,0,0,144,0,10,0,0};


/*  led3_blink
 *  Total Values: 100
 *  Total Generated Bytes: 25
 */ 
const I8U led3_blink[] = {172,0,10,192,0,168,0,10,128,0,164,0,10,0,0,160,0,10,64,0,164,0,10,128,0};


/*  led4_blink
 *  Total Values: 100
 *  Total Generated Bytes: 25
 */ 
const I8U led4_blink[] = {171,0,10,176,0,170,0,10,160,0,169,0,10,128,0,168,0,10,144,0,169,0,10,160,0};


/*  led5_blink
 *  Total Values: 100
 *  Total Generated Bytes: 25
 */ 
const I8U led5_blink[] = {170,192,10,172,0,170,128,10,168,0,170,64,10,160,0,170,0,10,164,0,170,64,10,168,0};


/*  led6_blink
 *  Total Values: 100
 *  Total Generated Bytes: 25
 */ 
const I8U led6_blink[] = {170,176,10,171,0,170,160,10,170,0,170,144,10,168,0,170,128,10,169,0,170,144,10,170,0};


/*  led7_blink
 *  Total Values: 100
 *  Total Generated Bytes: 25
 */ 
const I8U led7_blink[] = {170,172,10,170,192,170,168,10,170,128,170,164,10,170,0,170,160,10,170,64,170,164,10,170,128};


/*  led2_progress
 *  Total Values: 40
 *  Total Generated Bytes: 10
 */ 
const I8U led2_progress[] = {192,0,12,0,0,176,0,11,0,0};


/*  led3_progress
 *  Total Values: 50
 *  Total Generated Bytes: 13
 */ 
const I8U led3_progress[] = {192,0,12,0,0,176,0,11,0,0,172,0,0};


/*  led4_progress
 *  Total Values: 80
 *  Total Generated Bytes: 20
 */ 
const I8U led4_progress[] = {192,0,12,0,0,176,0,11,0,0,172,0,10,192,0,171,0,10,176,0};


/*  led5_progress
 *  Total Values: 90
 *  Total Generated Bytes: 23
 */ 
const I8U led5_progress[] = {192,0,12,0,0,176,0,11,0,0,172,0,10,192,0,171,0,10,172,0,170,192,0};


/*  led6_progress
 *  Total Values: 110
 *  Total Generated Bytes: 28
 */ 
const I8U led6_progress[] = {192,0,12,0,0,176,0,11,0,0,172,0,10,192,0,171,0,10,176,0,170,192,10,171,0,170,176,0};


/*  led7_progress
 *  Total Values: 120
 *  Total Generated Bytes: 30
 */ 
const I8U led7_progress[] = {192,0,11,0,0,176,0,10,192,0,172,0,10,176,0,171,0,10,172,0,170,192,10,171,0,170,172,10,170,192};


/*  pre_anim_no_goal_hit
 *  Total Values: 130
 *  Total Generated Bytes: 33
 */ 
const I8U pre_anim_no_goal_hit[] = {192,0,15,0,0,188,0,6,240,0,91,192,5,111,0,85,188,5,111,0,91,192,6,240,0,188,0,15,0,0,192,0,0};


/*  level2_goal
 *  Total Values: 350
 *  Total Generated Bytes: 88
 */ 
const I8U level2_goal[] = {192,0,15,0,0,188,0,10,240,0,171,192,6,175,0,90,188,61,106,195,245,168,59,213,131,175,88,122,189,71,106,244,117,171,203,214,172,175,90,138,189,88,154,245,137,171,212,214,175,113,90,189,77,106,225,245,169,235,213,176,175,89,90,189,104,106,245,214,175,113,90,189,77,106,225,245,169,235,213,176,175,89,90,189,104,106,245,208};


/*  unplugged_low_battery
 *  Total Values: 90
 *  Total Generated Bytes: 23
 */ 
const I8U unplugged_low_battery[] = {0,1,0,0,16,0,2,0,0,32,0,2,0,0,16,0,1,0,0,0,0,0,0};


/*  pairing
 *  Total Values: 130
 *  Total Generated Bytes: 33
 */ 
const I8U pairing[] = {64,1,1,0,16,4,1,0,16,32,0,66,0,1,48,0,7,0,1,32,0,66,0,16,32,4,1,1,0,16,64,1,0};


/*  charging0_40
 *  Total Values: 130
 *  Total Generated Bytes: 33
 */ 
const I8U charging0_40[] = {128,0,22,0,1,88,0,37,96,2,85,128,53,86,3,85,88,33,85,130,5,88,16,21,129,0,88,0,1,129,0,8,16};


/*  charging40_75
 *  Total Values: 130
 *  Total Generated Bytes: 33
 */ 
const I8U charging40_75[] = {128,1,6,0,16,88,2,69,96,36,85,131,133,86,56,85,90,65,85,164,5,89,0,21,144,0,88,0,1,148,0,9,64};


/*  charging75_99
 *  Total Values: 130
 *  Total Generated Bytes: 33
 */ 
const I8U charging75_99[] = {128,0,70,0,4,88,0,133,96,8,85,128,197,86,12,85,88,129,85,136,5,88,64,21,132,0,88,64,1,128,0,8,0};


/*  charging99_100
 *  Total Values: 70
 *  Total Generated Bytes: 18
 */ 
const I8U charging99_100[] = {149,84,134,85,72,89,84,133,101,72,85,148,133,86,72,85,88,128};
/* progress_1
 * 
 */ 
const I8U progress_1[] = {13,1,0,3};


/* progress_2
 * 
 */ 
const I8U progress_2[] = {13,1,7,1,1,5};


/* progress_3
 * 
 */ 
const I8U progress_3[] = {13,1,8,1,2,5};


/* progress_4
 * 
 */ 
const I8U progress_4[] = {13,1,9,1,3,5};


/* progress_5
 * 
 */ 
const I8U progress_5[] = {13,1,10,1,4,5};


/* progress_6
 * 
 */ 
const I8U progress_6[] = {13,1,11,1,5,5};


/* progress_7
 * 
 */ 
const I8U progress_7[] = {13,1,12,1,6,5};


/* level1_goal_hit
 * 
 */ 
const I8U level1_goal_hit[] = {14,1};


/* low_battery
 * 
 */ 
const I8U low_battery[] = {15,3};


/* bluetooth_pairing
 * 
 */ 
const I8U bluetooth_pairing[] = {16,0};


/* charging40
 * 
 */ 
const I8U charging40[] = {17,0};


/* charging75
 * 
 */ 
const I8U charging75[] = {18,0};


/* charging99
 * 
 */ 
const I8U charging99[] = {19,0};


/* charging100
 * 
 */ 
const I8U charging100[] = {20,0};


/* ble_error
 * 
 */ 


const I8U * level_2_pattern_ptrs[] = {
				led1_blink,  // 0
				led2_blink,  // 1
				led3_blink,  // 2
				led4_blink,  // 3
				led5_blink,  // 4
				led6_blink,  // 5
				led7_blink,  // 6
				led2_progress,  // 7
				led3_progress,  // 8
				led4_progress,  // 9
				led5_progress,  // 10
				led6_progress,  // 11
				led7_progress,  // 12
				pre_anim_no_goal_hit,  // 13
				level2_goal,  // 14
				unplugged_low_battery,  // 15
				pairing,  // 16
				charging0_40,  // 17
				charging40_75,  // 18
				charging75_99,  // 19
				charging99_100};  // 20

const I8U level_2_pattern_lens[] = {28,25,25,25,25,25,25,10,13,20,23,28,30,33,88,23,33,33,33,33,18};

const I8U * level_1_pattern_ptrs[] = {
				progress_1,  // 0
				progress_2,  // 1
				progress_3,  // 2
				progress_4,  // 3
				progress_5,  // 4
				progress_6,  // 5
				progress_7,  // 6
				level1_goal_hit,  // 7
				low_battery,  // 8
				bluetooth_pairing,  // 9
				charging40,  // 10
				charging75,  // 11
				charging99,  // 12
				charging100};   // 13

const I8U level_1_pattern_lens[] = {4,6,6,6,6,6,6,2,2,2,2,2,2,2};

#endif
