/***************************************************************************//**
 * File ui.h
 * 
 * Description: User Interface header
 *
 *
 ******************************************************************************/

#ifndef __UI_HEADER__
#define __UI_HEADER__

#define UI_CHARGING_DISPLAY_INTERVAL 2000
#define UI_LOGO_DISPLAY_INTERVAL 2000
#define UI_TEST_INTERVAL 1000

enum {
	// 0: Home
	UI_DISPLAY_HOME = 0,
	// 1: System
	UI_DISPLAY_DARK,
	UI_DISPLAY_CLING,
	UI_DISPLAY_OTA,
	UI_DISPLAY_PAIRING,    // 4
	// 2: a set of the typical use cases
	UI_DISPLAY_TRACKER,
	UI_DISPLAY_TRACKER_UV_IDX = UI_DISPLAY_TRACKER,
	UI_DISPLAY_TRACKER_STEP,
	UI_DISPLAY_TRACKER_SLEEP,
	UI_DISPLAY_TRACKER_DISTANCE,
	UI_DISPLAY_TRACKER_CALORIES,  // 9
	UI_DISPLAY_TRACKER_END = UI_DISPLAY_TRACKER_CALORIES,
	// 3: a set of smart features
	UI_DISPLAY_SMART,
	UI_DISPLAY_SMART_MESSAGE = UI_DISPLAY_SMART,
	UI_DISPLAY_SMART_APP_NOTIF,   // 11
	UI_DISPLAY_SMART_DETAIL_NOTIF,
	UI_DISPLAY_SMART_PHONE_FINDER,
	UI_DISPLAY_SMART_INCOMING_CALL,
	UI_DISPLAY_SMART_INCOMING_MESSAGE,
	UI_DISPLAY_SMART_REMINDER,
	UI_DISPLAY_SMART_WEATHER, // 13
	UI_DISPLAY_SMART_END = UI_DISPLAY_SMART_WEATHER,
	// 4: a set of VITAL
	UI_DISPLAY_VITAL,
	UI_DISPLAY_VITAL_HEART_RATE = UI_DISPLAY_VITAL,
	UI_DISPLAY_VITAL_SKIN_TEMP, // 15
	UI_DISPLAY_VITAL_END = UI_DISPLAY_VITAL_SKIN_TEMP,
	// 5: Special back panel mode
	UI_DISPLAY_SETTING,
	UI_DISPLAY_SETTING_VER = UI_DISPLAY_SETTING, // 16
	UI_DISPLAY_SETTING_END = UI_DISPLAY_SETTING_VER,
	// 6: Confirmation messages
	UI_DISPLAY_STOPWATCH,
	UI_DISPLAY_STOPWATCH_START = UI_DISPLAY_STOPWATCH,
	UI_DISPLAY_STOPWATCH_STOP,                        // 18
	UI_DISPLAY_STOPWATCH_HEARTRATE,
	UI_DISPLAY_STOPWATCH_CALORIES,
	UI_DISPLAY_STOPWATCH_RESULT,
	UI_DISPLAY_STOPWATCH_END = UI_DISPLAY_STOPWATCH_RESULT,
	// 7: Info menu
	UI_DISPLAY_WORKOUT,
	UI_DISPLAY_WORKOUT_WALKING = UI_DISPLAY_WORKOUT,  // 22
	UI_DISPLAY_WORKOUT_RUNNING,
	UI_DISPLAY_WORKOUT_ROW,
	UI_DISPLAY_WORKOUT_ELLIPTICAL,
	UI_DISPLAY_WORKOUT_STAIRS,
	UI_DISPLAY_WORKOUT_CYCLING,
	UI_DISPLAY_WORKOUT_AEROBIC,
	UI_DISPLAY_WORKOUT_PILOXING,
	UI_DISPLAY_WORKOUT_OTHERS,
	UI_DISPLAY_WORKOUT_INDOOR,
	UI_DISPLAY_WORKOUT_OUTDOOR,
	UI_DISPLAY_WORKOUT_END = UI_DISPLAY_WORKOUT_OUTDOOR,
	// 9: CAROUSEL
	UI_DISPLAY_CAROUSEL,
	UI_DISPLAY_CAROUSEL_1 = UI_DISPLAY_CAROUSEL, // workout + stopwatch + message, 33
	UI_DISPLAY_CAROUSEL_2, // uv + alarm + setting
	UI_DISPLAY_CAROUSEL_END = UI_DISPLAY_CAROUSEL_2,
	// 10: Remembered
	UI_DISPLAY_PREVIOUS,
	// The end
	UI_DISPLAY_MAXIMUM,
};

enum {
	ANIMATION_PANNING_IN,
	ANIMATION_PANNING_OUT,
	ANIMATION_TILTING_IN,
	ANIMATION_TILTING_OUT,
	ANIMATION_IRIS
};

enum {
	NOTIFICATION_TYPE_REMINDER,
	NOTIFICATION_TYPE_MESSAGE,
	NOTIFICATION_TYPE_IDLE_ALERT,
	NOTIFICATION_TYPE_HR,
};

enum {
	TRANSITION_DIR_NONE,
	TRANSITION_DIR_LEFT,
	TRANSITION_DIR_RIGHT,
	TRANSITION_DIR_UP,
	TRANSITION_DIR_DOWN
};

enum {
	LANGUAGE_TYPE_ENGLISH=0,
	LANGUAGE_TYPE_SIMPLIFIED_CHINESE,
	LANGUAGE_TYPE_TRADITIONAL_CHINESE
};

#define FRAME_DEPTH_CALORIES 7
#define FRAME_DEPTH_DISTANCE 7
#define FRAME_DEPTH_STEP 7
#define FRAME_DEPTH_SLEEP 7
#define FRAME_DEPTH_CLOCK 3
#define FRAME_DEPTH_WEATHER 2

typedef struct tagUI_ANIMATION_CTX {
	// All the dword variables
	I32U display_to_base;  // display timeout base
	I32U frame_interval;   // frame interval, i.e., the time interval that a particular frame stays on this frame
	I32U touch_time_stamp; // touch event time stamp
	
	// All the frame buffer related
	I8U p_oled_up[512];
	
	// State machine
	I8U state;
	BOOLEAN state_init;
	I8U prefer_state;
	
	// Boolean variables
	BOOLEAN display_active;
	
	// Animation
	I8U animation_mode;
	I8U direction;
	I8U animation_index;
	
	// Horizontal frame switching
	I8U frame_index;
	I8U frame_cached_index;
	I8U frame_prev_idx;
	I8U frame_next_idx;
	
	// Vertical switching
	I8U vertical_index;
	
	// App notific index
	I8U app_notific_index;
	
	// Page index
	I8U notif_detail_index;
	
  I8U string_pos_buf[5];	
	
	// Icon flashing
	BOOLEAN clock_sec_blinking;
	I8U heart_rate_wave_index;
	
	// True display
	BOOLEAN true_display;
	
	// Fonts type
	BOOLEAN fonts_type;
	
	// detail page
	BOOLEAN b_detail_page;
	
	// Clock orientation
	I8U clock_orientation;
	
	// Notification type
	I8U notif_type;
	
} UI_ANIMATION_CTX;

typedef enum {
	UI_STATE_IDLE = 0,
	UI_STATE_CLING_START,
	UI_STATE_HOME,
	UI_STATE_AUTHORIZATION,
	UI_STATE_CHARGING,
	UI_STATE_NOTIFICATIONS,
	UI_STATE_TOUCH_SENSING,
	UI_STATE_APPEAR,
	UI_STATE_ANIMATING,
	UI_STATE_CLOCK_GLANCE,
	UI_STATE_LOW_POWER,
	UI_STATE_SOS,
	UI_STATE_DARK,
} UI_ANIMATION_STATE;

enum {
	UI_TOP_MODE_NONE=0,
	UI_TOP_MODE_STEPS,
	UI_TOP_MODE_DISTANCE,
	UI_TOP_MODE_CALORIES,
	UI_TOP_MODE_SLEEP,
	UI_TOP_MODE_UV_IDX,
	UI_TOP_MODE_INCOMING_CALL,
	UI_TOP_MODE_MESSAGE,
	UI_TOP_MODE_HEART_RATE,
	UI_TOP_MODE_SKIN_TEMP,
	UI_TOP_MODE_WEATHER,
	UI_TOP_MODE_RETURN,
	UI_TOP_MODE_WORKOUT_START,
	UI_TOP_MODE_WORKOUT_STOP,
	UI_TOP_MODE_2DIGITS_INDEX,
	UI_TOP_MODE_REMINDER,
	UI_TOP_MODE_OK,
};

enum {
	UI_MIDDLE_MODE_NONE=0,
	UI_MIDDLE_MODE_CLOCK,
	UI_MIDDLE_MODE_STEPS,
	UI_MIDDLE_MODE_DISTANCE,
	UI_MIDDLE_MODE_CALORIES,
	UI_MIDDLE_MODE_UV_IDX,
	UI_MIDDLE_MODE_INCOMING_CALL,
	UI_MIDDLE_MODE_INCOMING_MESSAGE,
	UI_MIDDLE_MODE_PHONE_FINDER,
	UI_MIDDLE_MODE_SLEEP,
	UI_MIDDLE_MODE_MESSAGE,
	UI_MIDDLE_MODE_APP_NOTIF,
	UI_MIDDLE_MODE_DETAIL_NOTIF,
	UI_MIDDLE_MODE_HEART_RATE,
	UI_MIDDLE_MODE_SKIN_TEMP,
	UI_MIDDLE_MODE_WEATHER,
	UI_MIDDLE_MODE_BLE_CODE,
	UI_MIDDLE_MODE_LINKING,
	UI_MIDDLE_MODE_OTA,
	UI_MIDDLE_MODE_SOS,
	UI_MIDDLE_MODE_REMINDER,
};

enum {
	UI_BOTTOM_MODE_NONE=0,
	UI_BOTTOM_MODE_CLOCK,
	UI_BOTTOM_MODE_CALENDAR,
	UI_BOTTOM_MODE_CHARGING_PERCENTAGE,
	UI_BOTTOM_MODE_DELTA_DATE_BACKWARD,
	UI_BOTTOM_MODE_FIRMWARE_VER,
	UI_BOTTOM_MODE_2DIGITS_INDEX,
	UI_BOTTOM_MODE_APP_NOTIFIC_2DIGITS_INDEX,	
	UI_BOTTOM_MODE_MAX,
	UI_BOTTOM_MODE_MIN,
	UI_BOTTOM_MODE_OK,
};

enum {
	UI_FRAME_SLIDING_IN_DOWN,
	UI_FRAME_SLIDING_IN_UP,
	UI_FRAME_SLIDING_IN_LEFT,
	UI_FRAME_SLIDING_IN_RIGHT,
	UI_FRAME_SLIDING_OUT_DOWN,
	UI_FRAME_SLIDING_OUT_UP,
	UI_FRAME_SLIDING_OUT_LEFT,
	UI_FRAME_SLIDING_OUT_RIGHT,
};

void UI_state_machine(void);
void UI_init(void);
void UI_switch_state(I8U state, I32U interval);
void UI_test(void);
BOOLEAN UI_is_idle(void);
void UI_turn_on_display(UI_ANIMATION_STATE state, I32U time_offset);
void UI_reset_workout_mode(void);
#endif

